# Book settings
title: MA346 Course Notes
author: Nathan Carter
logo: logo.png

exclude_patterns: ["_static/*","README.md","_slides/*","experiments/*"]

repository:
  url: https://github.com/nathancarter/ma346-course-notes

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex

html:
  baseurl: "https://nathancarter.github.io/ma346-course-notes"

