# Book settings
title: MA346 Course Notes
author: Nathan Carter
logo: logo.png

exclude_patterns: ["README.md","_slides/*","experiments/*"]

repository:
  url: https://github.com/nathancarter/ma346-course-notes

html:
  baseurl: "https://nathancarter.github.io/ma346-course-notes"
  navbar_number_sections: true

latex:
  latex_documents:
    targetname: book.tex
